version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: clinica_db
    environment:
      MYSQL_DATABASE: clinica_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    # Opcional: Si quieres que la BD inicie con tablas ya creadas
    # volumes:
    #   - ./mysql-init:/docker-entrypoint-initdb.d

  api:
    build: 
      context: ./clinica-api  # Apunta a tu submódulo backend
    container_name: clinica_backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: 
      context: ./clinica-belleza-app # Apunta a tu submódulo frontend
    container_name: clinica_frontend
    ports:
      - "5173:5173"
    depends_on:
      - api